### ISSUE TITLE
problem with simGenerator configurator 

### ISSUE THREAD

**Issue by reginacaputo** [BurstCube/Simulation#18]
I tried to make a config.yaml file that was 1 energy bin and 1 cos(th) bin (100 keV at Zenith). (see attached file)
When it generated a source file, it put the source off axis: One.Beam FarfieldPointSource 57.3 0

What's the deal? 

[configE.txt](https://github.com/BurstCube/Simulation/files/1665166/configE.txt)

**Comment by kialio** [comment]
This is fixed in pull request #21
